eureka:
  host: discovery
  name: eureka
  port: 8081

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: users
              uri: lb://users
              predicates:
                - Path=/users,/users/**
              
  

            
