server:
  port: 0

spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://${eureka.host}:${eureka.port}/${eureka.name}
